// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_onBgusQB0QqE-hWe9aT8f4NVYDPeytk',
    appId: '1:763175119505:web:9a5e85f844a8edb6206d30',
    messagingSenderId: '763175119505',
    projectId: 'recappi-2022',
    authDomain: 'recappi-2022.firebaseapp.com',
    storageBucket: 'recappi-2022.appspot.com',
    measurementId: 'G-QCY5Z3RHB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0ijOCVcDY-pPZEKJfk_g9GfRkIgxbZc',
    appId: '1:763175119505:android:4197a451f87a406e206d30',
    messagingSenderId: '763175119505',
    projectId: 'recappi-2022',
    storageBucket: 'recappi-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALXKwHtQZzmGfCAZRZWbBE-Q_LdPznl5o',
    appId: '1:763175119505:ios:a88b956ec6066bd2206d30',
    messagingSenderId: '763175119505',
    projectId: 'recappi-2022',
    storageBucket: 'recappi-2022.appspot.com',
    iosClientId: '763175119505-64l0r35j633dofees9v3l9jatpuellmf.apps.googleusercontent.com',
    iosBundleId: 'com.recappi.app',
  );
}
